server:
  port: 8090
eureka:
  instance:
    hostname: springcloud-demo-eureka
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/